export const linking = {
  prefixes: ['http://localhost:8080'],
  config: {
    screens: {
      home: 'home',
      login: 'login',
      signOut: 'signOut',
      product: 'product',
      productDetail: 'product/productdetail',
      overview: 'overview',
      detailed: 'detailed',
      pickup: 'pickup',
      salesChannel: 'salesChannel',
      EmployeeProductivity: 'EmployeeProductivity',
      KPI: 'KPI',
      Warehouselocation: 'Warehouselocation',
      imports: 'imports',
      exports: 'exports',
      Inventory: 'inventory',
      transport: 'transport',
      Productivity: 'productivity',
      Utilities: 'utilities',
      inventory_management: 'inventory_management',
      dimension: 'dimension',
      products: 'products',
      user: 'user',
      locations: 'locations',
      equipment: 'equipment',
      configuration: 'configuration',
      report: 'report',
      exportData: 'exportData',
    },
  },
};
